In [107]:
#import bank marketing dataset
import pandas as pd
bank_full = pd.read_csv(r'C:\Users\wangs\Documents\SHAN WANG\springBoard\Project\BANK MARKETING DATASET\bank-full.csv', delimiter = ';')

In [108]:
print (bank_full.head())
print (bank_full.shape)

   age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no  
(45211, 17)


In [109]:
#Divide dataset into trainX, trainY, testX, testY 
from sklearn.model_selection import train_test_split 
X = bank_full.drop(['y'], axis = 1).values
y = bank_full['y'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [110]:
print (X_train[:10])
print (X_train.shape)

[[29 'housemaid' 'single' 'tertiary' 'no' 453 'no' 'no' 'cellular' 13
  'aug' 126 2 -1 0 'unknown']
 [55 'services' 'married' 'secondary' 'no' 0 'no' 'no' 'cellular' 22
  'oct' 102 1 106 1 'failure']
 [56 'services' 'divorced' 'secondary' 'no' 935 'no' 'no' 'cellular' 2
  'jun' 136 1 96 3 'failure']
 [47 'housemaid' 'single' 'tertiary' 'no' 3232 'no' 'no' 'telephone' 6
  'oct' 541 1 204 3 'failure']
 [39 'technician' 'married' 'tertiary' 'no' 508 'no' 'no' 'cellular' 2
  'nov' 154 3 -1 0 'unknown']
 [36 'technician' 'single' 'tertiary' 'no' 306 'no' 'no' 'cellular' 14
  'aug' 111 2 -1 0 'unknown']
 [33 'management' 'single' 'tertiary' 'no' 6807 'no' 'no' 'cellular' 20
  'apr' 163 1 -1 0 'unknown']
 [36 'management' 'married' 'tertiary' 'no' 669 'no' 'no' 'unknown' 9
  'jun' 91 1 -1 0 'unknown']
 [52 'retired' 'married' 'secondary' 'no' 1956 'no' 'no' 'unknown' 6
  'jun' 384 2 -1 0 'unknown']
 [53 'management' 'married' 'tertiary' 'no' 694 'no' 'no' 'unknown' 18
  'jun' 130 6 -1 0 'unkn

In [111]:
print (y)

['no' 'no' 'no' ... 'yes' 'no' 'no']


In [112]:
#Identify numeric and categorical variables 
total_columns = bank_full.columns
print (total_columns)

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')


In [116]:
num_columns = list(bank_full._get_numeric_data().columns)
print (num_columns)

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']


In [117]:
cat_columns = list(set(total_columns) - set(num_columns))
print (cat_columns)

['poutcome', 'default', 'marital', 'loan', 'y', 'contact', 'education', 'month', 'job', 'housing']


In [118]:
#apply one-hot encoding/dummy coding
from sklearn import preprocessing 
enc = preprocessing.OneHotEncoder(handle_unknown='ignore')
enc.fit(bank_full[cat_columns])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=True)

In [119]:
#View the categories of each feature determined during fitting
print (enc.categories_)

[array(['failure', 'other', 'success', 'unknown'], dtype=object), array(['no', 'yes'], dtype=object), array(['divorced', 'married', 'single'], dtype=object), array(['no', 'yes'], dtype=object), array(['no', 'yes'], dtype=object), array(['cellular', 'telephone', 'unknown'], dtype=object), array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object), array(['apr', 'aug', 'dec', 'feb', 'jan', 'jul', 'jun', 'mar', 'may',
       'nov', 'oct', 'sep'], dtype=object), array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object), array(['no', 'yes'], dtype=object)]


In [120]:
#View dummy values
preprocessing.OneHotEncoder(handle_unknown='ignore')
print (enc.transform(bank_full[cat_columns]).toarray())

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]]


In [122]:
#Standardization,mean removal and variance scaling on the train set
X_train_df = pd.DataFrame(data = X_train, columns = bank_full.drop(['y'], axis = 1).columns)
X_train_df_num = X_train_df[num_columns]
X_scaled = preprocessing.scale(X_train_df_num)

In [123]:
X_scaled

array([[-1.12412874, -0.30427051, -0.33930524, ..., -0.24359804,
        -0.41046341, -0.3059401 ],
       [ 1.32276575, -0.457537  ,  0.74284423, ..., -0.5618293 ,
         0.65312148,  0.22504206],
       [ 1.41687707, -0.14119225, -1.66193236, ..., -0.5618293 ,
         0.55372102,  1.28700638],
       ...,
       [-0.65357211, -0.01194766, -0.09882758, ..., -0.5618293 ,
        -0.41046341, -0.3059401 ],
       [-0.74768343, -0.40171145, -1.06073821, ..., -0.5618293 ,
        -0.41046341, -0.3059401 ],
       [-0.2771268 , -0.4714088 ,  0.6226054 , ...,  2.30225204,
        -0.41046341, -0.3059401 ]])

In [124]:
# Compute the mean and standard deviation on the testing set
scaler = preprocessing.StandardScaler().fit(X_train_df_num)
X_test_df = pd.DataFrame(data = X_test, columns = bank_full.drop(['y'], axis = 1).columns)
X_test_df_num = X_test_df[num_columns]
scaler.transform(X_test_df_num)

array([[-0.08890415, -0.26130175,  0.02141125, ..., -0.5618293 ,
        -0.41046341, -0.3059401 ],
       [ 0.56987513,  0.77536168, -0.82026055, ..., -0.24359804,
        -0.41046341, -0.3059401 ],
       [-1.50057405, -0.27551189,  0.50236657, ..., -0.5618293 ,
        -0.41046341, -0.3059401 ],
       ...,
       [-0.2771268 , -0.457537  ,  0.14165008, ..., -0.24359804,
        -0.41046341, -0.3059401 ],
       [-0.93590609,  0.52871427,  1.70475486, ..., -0.5618293 ,
         0.45432056,  0.22504206],
       [-0.65357211,  1.57688115,  0.26188891, ..., -0.5618293 ,
        -0.41046341, -0.3059401 ]])